// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iigbqibfsbffpztdizmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpZ2JxaWJmc2JmZnB6dGRpem13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNjQ1MTksImV4cCI6MjA2Mjc0MDUxOX0.C5FAlpkAZRxDlvX-4qx3Kwb-lvZDkXd_oa7TS2FTuR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);